apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: toplist
  labels:
    app: toplist-backend
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/toplistdb"
  SPRING_DATASOURCE_USERNAME: "toplist"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
  SERVER_PORT: "8080"
  LOGGING_LEVEL_COM_TOPLIST: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: toplist
  labels:
    app: toplist-backend
type: Opaque
data:
  # password123 base64 encoded
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQxMjM=
