apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: toplist
  labels:
    app: postgresql
data:
  POSTGRES_DB: toplistdb
  POSTGRES_USER: toplist
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: toplist
  labels:
    app: postgresql
type: Opaque
data:
  # password123 base64 encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
