server:
  port: 8080

spring:
  application:
    name: toplist-app
  
  datasource:
    url: jdbc:postgresql://database:5432/toplistdb
    driver-class-name: org.postgresql.Driver
    username: toplist
    password: password123
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.toplist: INFO
    org.springframework.web: INFO
